name: PR
on: [pull_request]

jobs:
  maxwell-bridge-checker:
    strategy:
      matrix:
        step: ['lint', 'build']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ${{ matrix.step }}
      run: |
        cd maxwell-bridge
        yarn
        yarn ${{ matrix.step }}
  mainnet-bridge-checker:
    strategy:
      matrix:
        step: ['lint', 'build']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ${{ matrix.step }}
      run: |
        cd mainnet-bridge
        yarn
        yarn ${{ matrix.step }}